# Generated by Django 2.1.1 on 2018-10-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('CourseName', models.CharField(max_length=50)),
                ('CourseId', models.IntegerField(default=5, primary_key=True, serialize=False)),
                ('CourseFee', models.IntegerField(default=5)),
                ('CourseDuration', models.IntegerField(default=3)),
            ],
        ),
    ]
