# Generated by Django 2.1.1 on 2018-10-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculity',
            fields=[
                ('id', models.IntegerField(default=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('cno', models.IntegerField(default=10)),
                ('course', models.CharField(max_length=30)),
                ('exp', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
