# Generated by Django 2.1.1 on 2018-10-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_faculity'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('password', models.IntegerField(default=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
