# Generated by Django 2.1.1 on 2018-10-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyregister',
            fields=[
                ('c_id', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_hrname', models.CharField(max_length=50)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_contact', models.IntegerField(default=10)),
                ('c_purpose', models.CharField(max_length=50)),
                ('c_address', models.CharField(max_length=100)),
            ],
        ),
    ]
