# Generated by Django 2.1.1 on 2018-10-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_companyregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregister',
            name='c_status',
            field=models.IntegerField(default=30),
        ),
    ]
