# Generated by Django 2.1.1 on 2018-10-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_companyregister_c_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregister',
            name='c_status',
            field=models.CharField(max_length=30),
        ),
    ]
